### ISSUE TITLE
Error running the model

### ISSUE THREAD

**Issue by matiasurbieta** [francomahl/sswmfa#1]
After creating the ER model, I modeled a simple navigation model where it should be shown a list of entities.
When trying to run the app, I get the following error:

POST /createFile 200 0.561 ms - -
[nodemon] restarting due to changes...
File created!
[nodemon] starting `node ./bin/www`
Sat, 12 May 2018 11:03:19 GMT sequelize deprecated String based operators are now deprecated. Please use Symbol based operators for better security, read more at http://docs.sequelizejs.com/manual/tutorial/querying.html#operators at node_modules/sequelize/lib/sequelize.js:242:13
Sat, 12 May 2018 11:03:19 GMT sswmfa:server Listening on port 3000
POST /createFile 200 15.471 ms - -
POST /createFile 200 0.852 ms - -
{ Error: ENOENT: no such file or directory, open '/app/views/rendered/index.jade'
  errno: -2,
  code: 'ENOENT',
  syscall: 'open',
  path: '/app/views/rendered/index.jade' }
{ Error: ENOENT: no such file or directory, open '/app/views/rendered/formUpdateOneInClass.jade'
  errno: -2,
  code: 'ENOENT',
  syscall: 'open',
  path: '/app/views/rendered/formUpdateOneInClass.jade' }
POST /createFile 200 0.359 ms - -
{ Error: ENOENT: no such file or directory, open '/app/views/rendered/detailFromClass.jade'
  errno: -2,
  code: 'ENOENT',
  syscall: 'open',
  path: '/app/views/rendered/detailFromClass.jade' }
Executing (default): SELECT `id`, `nombre`, `email`, `createdAt`, `updatedAt` FROM `Classes` AS `Class`;
GET /render 500 284.858 ms - 2124
Error: Failed to lookup view "error" in views directory "/app/views"
    at Function.render (/app/node_modules/express/lib/application.js:580:17)
    at ServerResponse.render (/app/node_modules/express/lib/response.js:1008:7)
    at /app/app.js:41:7
    at Layer.handle_error (/app/node_modules/express/lib/router/layer.js:71:5)
    at trim_prefix (/app/node_modules/express/lib/router/index.js:315:13)
    at /app/node_modules/express/lib/router/index.js:284:7
    at Function.process_params (/app/node_modules/express/lib/router/index.js:335:12)
    at next (/app/node_modules/express/lib/router/index.js:275:10)
    at Layer.handle_error (/app/node_modules/express/lib/router/layer.js:67:12)
    at trim_prefix (/app/node_modules/express/lib/router/index.js:315:13)
    at /app/node_modules/express/lib/router/index.js:284:7
    at Function.process_params (/app/node_modules/express/lib/router/index.js:335:12)
    at next (/app/node_modules/express/lib/router/index.js:275:10)
    at /app/node_modules/express/lib/router/index.js:635:15
    at IncomingMessage.next (/app/node_modules/express/lib/router/index.js:260:14)
    at done (/app/node_modules/express/lib/response.js:1003:25)
    at Function.render (/app/node_modules/express/lib/application.js:582:14)
    at ServerResponse.render (/app/node_modules/express/lib/response.js:1008:7)
    at sequelize.models.Class.findAll.then.recordsFromClass (/app/routes/render.js:7:8)
    at tryCatcher (/app/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/app/node_modules/bluebird/js/release/promise.js:512:31)
    at Promise._settlePromise (/app/node_modules/bluebird/js/release/promise.js:569:18) 

The model is:

{ "class": "go.GraphLinksModel",
  "copiesArrays": true,
  "copiesArrayObjects": true,
  "modelData": {"position":"-508.84404500084605 -31.525893497466996"},
  "nodeDataArray": [ 
{"name":"Index", "isGroup":true, "category":"MainPage", "key":-1},
{"category":"List", "name":"List", "class":"Class", "fields":[ {"name":"nombre", "type":"text", "unique":false, "nullable":false, "display":true},{"name":"email", "type":"text", "unique":false, "nullable":false, "display":true} ], "comments":"", "key":-2, "loc":"-20 200", "group":-1, "detail":true, "edit":true, "delete":true}
 ],
  "linkDataArray": []}

The navigation model is:

{ "class": "go.GraphLinksModel",
  "copiesArrays": true,
  "copiesArrayObjects": true,
  "modelData": {"position":"-508.84404500084605 -31.525893497466996"},
  "nodeDataArray": [ 
{"name":"Index", "isGroup":true, "category":"MainPage", "key":-1},
{"category":"List", "name":"List", "class":"Class", "fields":[ {"name":"nombre", "type":"text", "unique":false, "nullable":false, "display":true},{"name":"email", "type":"text", "unique":false, "nullable":false, "display":true} ], "comments":"", "key":-2, "loc":"-20 200", "group":-1, "detail":true, "edit":true, "delete":true}
 ],
  "linkDataArray": []}

**Comment by francomahl** [comment]
Thanks!
I forgot to add the following steps.
$ mkdir /public/rendered
$ mkdir /views/rendered

Now the README.md is updated with these instructions.
